/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageDataRouteImport } from './routes/manage-data'
import { Route as SocialAdsRouteImport } from './routes/social-ads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageDataRoute = ManageDataRouteImport.update({
  id: '/manage-data',
  path: '/manage-data',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialAdsRoute = SocialAdsRouteImport.update({
  id: '/social-ads',
  path: '/social-ads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manage-data': typeof ManageDataRoute
  '/social-ads': typeof SocialAdsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manage-data': typeof ManageDataRoute
  '/social-ads': typeof SocialAdsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manage-data': typeof ManageDataRoute
  '/social-ads': typeof SocialAdsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/manage-data' | '/social-ads'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/manage-data' | '/social-ads'
  id: '__root__' | '/' | '/manage-data' | '/social-ads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManageDataRoute: typeof ManageDataRoute
  SocialAdsRoute: typeof SocialAdsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-data': {
      id: '/manage-data'
      path: '/manage-data'
      fullPath: '/manage-data'
      preLoaderRoute: typeof ManageDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-ads': {
      id: '/social-ads'
      path: '/social-ads'
      fullPath: '/social-ads'
      preLoaderRoute: typeof SocialAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManageDataRoute: ManageDataRoute,
  SocialAdsRoute: SocialAdsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
